services:
  - type: web
    name: setgame-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: setgame-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: setgame-db
    plan: free
    databaseName: setgame
    user: setgame_user





